version: '3.8'

services:
  db:
    image: "postgres:9.6-alpine"
    container_name: "postgres_db"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=backend-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    image: app
    container_name: backend-dimed
    ports:
      - "8082:8082"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/backend-api
    depends_on:
      - db

volumes:
  postgresql-data: